### ISSUE TITLE
初版Demo开发

### ISSUE THREAD

**Issue by destinyd** [mindpin/knowledge-camp-art#4]
mockup地址
http://www.mindpin.com/mockups/kc/art-camp_20150920/

版本库地址
https://github.com/destinyd/art-demo

预计完成时间
9月28日

提交物
Android版Demo

**Comment by destinyd** [comment]
现难点主要为：
1. 摄像头 **扫描框** 自动对应素描纸张(java有库，但是不知道效果)，并拍照
2. 退一步方案，通过手势改变 **扫描框** 形状、大小，也还是需要一段时间去研究对应API

**Comment by destinyd** [comment]
实现手动拍照的时候也遇到了问题：  
1. 拍照提交页面方框4个角(改用实线实现)
2. 拍照提交页面 截取拍照框内 对应的图片(已尝试几种方式，都存在偏差，在看源码进行微调)

可能还需要一点时间来实现

**Comment by ben7th** [comment]
加油！

**Comment by destinyd** [comment]
放假前已经完成拍照那块了

**Comment by ben7th** [comment]
第一版 demo 下载地址：
http://pan.baidu.com/s/1hqeyJ9y

---

目前发现的问题：
在宋亮的手机上（nexus 5, 原生 5.0 系统），点击拍照会报错（也可能是宋亮手机本身的问题。需要其他人测试）

@advancer @fushang318

**Comment by destinyd** [comment]
已知问题：
虚拟机(4.2.2)，进入拍照页也会报错。原来使用是正常的，OS X更新后出现

**Comment by fushang318** [comment]
大神F2 移动版（4.4.2）
点击 画完了!点击拍照提交 就会报错，堆栈如下

```
10-09 12:01:24.015 3911-3911/com.mindpin.art_demo.samples I/View: Touch up dispatch to android.widget.Button{4208ca50 VFED..C. ...P.... 0,1034-720,1134 #7f090004 app:id/btn_next}, event = MotionEvent { action=ACTION_UP, id[0]=0, x[0]=538.25244, y[0]=80.015625, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=1823330, downTime=1823191, deviceId=2, source=0x1002 }
10-09 12:01:24.016 3911-3911/com.mindpin.art_demo.samples V/Provider/Settings:  from settings cache , name = sound_effects_enabled , value = 0
10-09 12:01:24.504 3911-3911/com.mindpin.art_demo.samples V/PhoneWindow: DecorView setVisiblity: visibility = 4 ,Parent =null, this =com.android.internal.policy.impl.PhoneWindow$DecorView{422852e8 I.E..... R.....ID 0,0-0,0}
10-09 12:01:24.509 3911-3911/com.mindpin.art_demo.samples V/PhoneWindow: DecorView setVisiblity: visibility = 0 ,Parent =ViewRoot{42290d90 com.mindpin.art_demo.samples/com.mindpin.art_demo.samples.views.StepActivity,ident = 3}, this =com.android.internal.policy.impl.PhoneWindow$DecorView{422852e8 V.E..... R.....ID 0,0-0,0}
10-09 12:01:24.640 3911-3911/com.mindpin.art_demo.samples V/PhoneWindow: DecorView setVisiblity: visibility = 4 ,Parent =ViewRoot{41ec47c0 com.mindpin.art_demo.samples/com.mindpin.art_demo.samples.views.ChapterActivity,ident = 2}, this =com.android.internal.policy.impl.PhoneWindow$DecorView{41f9b3b0 I.E..... R....... 0,0-720,1280}
10-09 12:01:27.022 3911-3911/com.mindpin.art_demo.samples I/View: Touch down dispatch to android.widget.Button{41f4fa18 VFED..C. ........ 0,1034-720,1134 #7f090004 app:id/btn_next}, event = MotionEvent { action=ACTION_DOWN, id[0]=0, x[0]=509.29266, y[0]=65.02734, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=1826336, downTime=1826336, deviceId=2, source=0x1002 }
10-09 12:01:27.164 3911-3911/com.mindpin.art_demo.samples I/View: Touch up dispatch to android.widget.Button{41f4fa18 VFED..C. ...P.... 0,1034-720,1134 #7f090004 app:id/btn_next}, event = MotionEvent { action=ACTION_UP, id[0]=0, x[0]=509.29266, y[0]=65.02734, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=1826474, downTime=1826336, deviceId=2, source=0x1002 }
10-09 12:01:27.178 3911-3911/com.mindpin.art_demo.samples V/Provider/Settings:  from settings cache , name = sound_effects_enabled , value = 0
10-09 12:01:28.006 3911-3911/com.mindpin.art_demo.samples W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x41aded40)
10-09 12:01:28.007 3911-3911/com.mindpin.art_demo.samples W/dalvikvm: threadid=1: uncaught exception occurred
10-09 12:01:28.007 3911-3911/com.mindpin.art_demo.samples W/System.err: java.lang.RuntimeException: Unable to resume activity {com.mindpin.art_demo.samples/com.mindpin.art_demo.samples.views.TakePhotoActivity}: java.lang.RuntimeException: autoFocus failed
10-09 12:01:28.007 3911-3911/com.mindpin.art_demo.samples W/System.err:     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2985)
10-09 12:01:28.008 3911-3911/com.mindpin.art_demo.samples W/System.err:     at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3014)
10-09 12:01:28.008 3911-3911/com.mindpin.art_demo.samples W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2403)
10-09 12:01:28.008 3911-3911/com.mindpin.art_demo.samples W/System.err:     at android.app.ActivityThread.access$800(ActivityThread.java:159)
10-09 12:01:28.008 3911-3911/com.mindpin.art_demo.samples W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1329)
10-09 12:01:28.008 3911-3911/com.mindpin.art_demo.samples W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:110)
10-09 12:01:28.008 3911-3911/com.mindpin.art_demo.samples W/System.err:     at android.os.Looper.loop(Looper.java:193)
10-09 12:01:28.009 3911-3911/com.mindpin.art_demo.samples W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5367)
10-09 12:01:28.009 3911-3911/com.mindpin.art_demo.samples W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
10-09 12:01:28.009 3911-3911/com.mindpin.art_demo.samples W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
10-09 12:01:28.009 3911-3911/com.mindpin.art_demo.samples W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:847)
10-09 12:01:28.009 3911-3911/com.mindpin.art_demo.samples W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:663)
10-09 12:01:28.009 3911-3911/com.mindpin.art_demo.samples W/System.err:     at dalvik.system.NativeStart.main(Native Method)
10-09 12:01:28.009 3911-3911/com.mindpin.art_demo.samples W/System.err: Caused by: java.lang.RuntimeException: autoFocus failed
10-09 12:01:28.013 3911-3911/com.mindpin.art_demo.samples W/System.err:     at android.hardware.Camera.native_autoFocus(Native Method)
10-09 12:01:28.013 3911-3911/com.mindpin.art_demo.samples W/System.err:     at android.hardware.Camera.autoFocus(Camera.java:1454)
10-09 12:01:28.014 3911-3911/com.mindpin.art_demo.samples W/System.err:     at com.mindpin.art_demo.samples.views.TakePhotoActivity.focus(TakePhotoActivity.java:117)
10-09 12:01:28.014 3911-3911/com.mindpin.art_demo.samples W/System.err:     at com.mindpin.art_demo.samples.views.TakePhotoActivity.onResume(TakePhotoActivity.java:451)
10-09 12:01:28.015 3911-3911/com.mindpin.art_demo.samples W/System.err:     at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1197)
10-09 12:01:28.015 3911-3911/com.mindpin.art_demo.samples W/System.err:     at android.app.Activity.performResume(Activity.java:5358)
10-09 12:01:28.015 3911-3911/com.mindpin.art_demo.samples W/System.err:     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2971)
10-09 12:01:28.016 3911-3911/com.mindpin.art_demo.samples W/System.err:     ... 12 more
10-09 12:01:28.016 3911-3911/com.mindpin.art_demo.samples W/dalvikvm: threadid=1: calling UncaughtExceptionHandler
10-09 12:01:28.018 3911-3911/com.mindpin.art_demo.samples E/AndroidRuntime: FATAL EXCEPTION: main
10-09 12:01:28.018 3911-3911/com.mindpin.art_demo.samples E/AndroidRuntime: Process: com.mindpin.art_demo.samples, PID: 3911
10-09 12:01:28.018 3911-3911/com.mindpin.art_demo.samples E/AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {com.mindpin.art_demo.samples/com.mindpin.art_demo.samples.views.TakePhotoActivity}: java.lang.RuntimeException: autoFocus failed
10-09 12:01:28.018 3911-3911/com.mindpin.art_demo.samples E/AndroidRuntime:     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2985)
10-09 12:01:28.018 3911-3911/com.mindpin.art_demo.samples E/AndroidRuntime:     at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3014)
10-09 12:01:28.018 3911-3911/com.mindpin.art_demo.samples E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2403)
10-09 12:01:28.018 3911-3911/com.mindpin.art_demo.samples E/AndroidRuntime:     at android.app.ActivityThread.access$800(ActivityThread.java:159)
10-09 12:01:28.018 3911-3911/com.mindpin.art_demo.samples E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1329)
10-09 12:01:28.018 3911-3911/com.mindpin.art_demo.samples E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:110)
10-09 12:01:28.018 3911-3911/com.mindpin.art_demo.samples E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:193)
10-09 12:01:28.018 3911-3911/com.mindpin.art_demo.samples E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5367)
10-09 12:01:28.018 3911-3911/com.mindpin.art_demo.samples E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method)
10-09 12:01:28.018 3911-3911/com.mindpin.art_demo.samples E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:515)
10-09 12:01:28.018 3911-3911/com.mindpin.art_demo.samples E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:847)
10-09 12:01:28.018 3911-3911/com.mindpin.art_demo.samples E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:663)
10-09 12:01:28.018 3911-3911/com.mindpin.art_demo.samples E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method)
10-09 12:01:28.018 3911-3911/com.mindpin.art_demo.samples E/AndroidRuntime:  Caused by: java.lang.RuntimeException: autoFocus failed
10-09 12:01:28.018 3911-3911/com.mindpin.art_demo.samples E/AndroidRuntime:     at android.hardware.Camera.native_autoFocus(Native Method)
10-09 12:01:28.018 3911-3911/com.mindpin.art_demo.samples E/AndroidRuntime:     at android.hardware.Camera.autoFocus(Camera.java:1454)
10-09 12:01:28.018 3911-3911/com.mindpin.art_demo.samples E/AndroidRuntime:     at com.mindpin.art_demo.samples.views.TakePhotoActivity.focus(TakePhotoActivity.java:117)
10-09 12:01:28.018 3911-3911/com.mindpin.art_demo.samples E/AndroidRuntime:     at com.mindpin.art_demo.samples.views.TakePhotoActivity.onResume(TakePhotoActivity.java:451)
10-09 12:01:28.018 3911-3911/com.mindpin.art_demo.samples E/AndroidRuntime:     at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1197)
10-09 12:01:28.018 3911-3911/com.mindpin.art_demo.samples E/AndroidRuntime:     at android.app.Activity.performResume(Activity.java:5358)
10-09 12:01:28.018 3911-3911/com.mindpin.art_demo.samples E/AndroidRuntime:     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2971)
10-09 12:01:28.018 3911-3911/com.mindpin.art_demo.samples E/AndroidRuntime:     at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3014) 
10-09 12:01:28.018 3911-3911/com.mindpin.art_demo.samples E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2403) 
10-09 12:01:28.018 3911-3911/com.mindpin.art_demo.samples E/AndroidRuntime:     at android.app.ActivityThread.access$800(ActivityThread.java:159) 
10-09 12:01:28.018 3911-3911/com.mindpin.art_demo.samples E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1329) 
10-09 12:01:28.018 3911-3911/com.mindpin.art_demo.samples E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:110) 
10-09 12:01:28.018 3911-3911/com.mindpin.art_demo.samples E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:193) 
10-09 12:01:28.018 3911-3911/com.mindpin.art_demo.samples E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5367) 
10-09 12:01:28.018 3911-3911/com.mindpin.art_demo.samples E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method) 
10-09 12:01:28.018 3911-3911/com.mindpin.art_demo.samples E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:515) 
10-09 12:01:28.018 3911-3911/com.mindpin.art_demo.samples E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:847) 
10-09 12:01:28.018 3911-3911/com.mindpin.art_demo.samples E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:663) 
10-09 12:01:28.018 3911-3911/com.mindpin.art_demo.samples E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method) 
```

**Comment by advancer-zz** [comment]
可能是底层依赖包中的某些调用或依赖异常吧。能否退回到更新以前

**Comment by destinyd** [comment]
@fushang318 这个问题是对焦出现的问题，我可以尝试先把对焦取消掉

**Comment by destinyd** [comment]
已取消自动对焦，最新版本，百度云地址：

http://pan.baidu.com/s/1bnluPUf

@ben7th @fushang318 @advancer

**Comment by fushang318** [comment]
点击 画完了!点击拍照提交 就会报错的问题已经没有了

我个人觉得有两个可以进一步完善的地方
1. 对焦 还是很有必要的，讨论一下如何去做对焦的功能
2. 目前页面堆栈没有进行设计，点击后退都是返回前一个页面，需要讨论一下页面堆栈具体的做法

**Comment by destinyd** [comment]
@fushang318 
对焦我也觉得很必要，但是自己真机、虚拟机测试都通过，其余机型出错，可能并没有那么多对应的真机去测试。
