### ISSUE TITLE
点击【拍照提交】报错

### ISSUE THREAD

**Issue by destinyd** [mindpin/knowledge-camp-art#5]
from 李飞

大神F2 移动版（4.4.2）
点击 画完了!点击拍照提交 就会报错，堆栈如下

```
10-09 12:01:24.015 3911-3911/com.mindpin.art_demo.samples I/View: Touch up dispatch to android.widget.Button{4208ca50 VFED..C. ...P.... 0,1034-720,1134 #7f090004 app:id/btn_next}, event = MotionEvent { action=ACTION_UP, id[0]=0, x[0]=538.25244, y[0]=80.015625, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=1823330, downTime=1823191, deviceId=2, source=0x1002 }
10-09 12:01:24.016 3911-3911/com.mindpin.art_demo.samples V/Provider/Settings:  from settings cache , name = sound_effects_enabled , value = 0
10-09 12:01:24.504 3911-3911/com.mindpin.art_demo.samples V/PhoneWindow: DecorView setVisiblity: visibility = 4 ,Parent =null, this =com.android.internal.policy.impl.PhoneWindow$DecorView{422852e8 I.E..... R.....ID 0,0-0,0}
10-09 12:01:24.509 3911-3911/com.mindpin.art_demo.samples V/PhoneWindow: DecorView setVisiblity: visibility = 0 ,Parent =ViewRoot{42290d90 com.mindpin.art_demo.samples/com.mindpin.art_demo.samples.views.StepActivity,ident = 3}, this =com.android.internal.policy.impl.PhoneWindow$DecorView{422852e8 V.E..... R.....ID 0,0-0,0}
10-09 12:01:24.640 3911-3911/com.mindpin.art_demo.samples V/PhoneWindow: DecorView setVisiblity: visibility = 4 ,Parent =ViewRoot{41ec47c0 com.mindpin.art_demo.samples/com.mindpin.art_demo.samples.views.ChapterActivity,ident = 2}, this =com.android.internal.policy.impl.PhoneWindow$DecorView{41f9b3b0 I.E..... R....... 0,0-720,1280}
10-09 12:01:27.022 3911-3911/com.mindpin.art_demo.samples I/View: Touch down dispatch to android.widget.Button{41f4fa18 VFED..C. ........ 0,1034-720,1134 #7f090004 app:id/btn_next}, event = MotionEvent { action=ACTION_DOWN, id[0]=0, x[0]=509.29266, y[0]=65.02734, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=1826336, downTime=1826336, deviceId=2, source=0x1002 }
10-09 12:01:27.164 3911-3911/com.mindpin.art_demo.samples I/View: Touch up dispatch to android.widget.Button{41f4fa18 VFED..C. ...P.... 0,1034-720,1134 #7f090004 app:id/btn_next}, event = MotionEvent { action=ACTION_UP, id[0]=0, x[0]=509.29266, y[0]=65.02734, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=1826474, downTime=1826336, deviceId=2, source=0x1002 }
10-09 12:01:27.178 3911-3911/com.mindpin.art_demo.samples V/Provider/Settings:  from settings cache , name = sound_effects_enabled , value = 0
10-09 12:01:28.006 3911-3911/com.mindpin.art_demo.samples W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x41aded40)
10-09 12:01:28.007 3911-3911/com.mindpin.art_demo.samples W/dalvikvm: threadid=1: uncaught exception occurred
10-09 12:01:28.007 3911-3911/com.mindpin.art_demo.samples W/System.err: java.lang.RuntimeException: Unable to resume activity {com.mindpin.art_demo.samples/com.mindpin.art_demo.samples.views.TakePhotoActivity}: java.lang.RuntimeException: autoFocus failed
10-09 12:01:28.007 3911-3911/com.mindpin.art_demo.samples W/System.err:     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2985)
10-09 12:01:28.008 3911-3911/com.mindpin.art_demo.samples W/System.err:     at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3014)
10-09 12:01:28.008 3911-3911/com.mindpin.art_demo.samples W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2403)
10-09 12:01:28.008 3911-3911/com.mindpin.art_demo.samples W/System.err:     at android.app.ActivityThread.access$800(ActivityThread.java:159)
10-09 12:01:28.008 3911-3911/com.mindpin.art_demo.samples W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1329)
10-09 12:01:28.008 3911-3911/com.mindpin.art_demo.samples W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:110)
10-09 12:01:28.008 3911-3911/com.mindpin.art_demo.samples W/System.err:     at android.os.Looper.loop(Looper.java:193)
10-09 12:01:28.009 3911-3911/com.mindpin.art_demo.samples W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5367)
10-09 12:01:28.009 3911-3911/com.mindpin.art_demo.samples W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
10-09 12:01:28.009 3911-3911/com.mindpin.art_demo.samples W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
10-09 12:01:28.009 3911-3911/com.mindpin.art_demo.samples W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:847)
10-09 12:01:28.009 3911-3911/com.mindpin.art_demo.samples W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:663)
10-09 12:01:28.009 3911-3911/com.mindpin.art_demo.samples W/System.err:     at dalvik.system.NativeStart.main(Native Method)
10-09 12:01:28.009 3911-3911/com.mindpin.art_demo.samples W/System.err: Caused by: java.lang.RuntimeException: autoFocus failed
10-09 12:01:28.013 3911-3911/com.mindpin.art_demo.samples W/System.err:     at android.hardware.Camera.native_autoFocus(Native Method)
10-09 12:01:28.013 3911-3911/com.mindpin.art_demo.samples W/System.err:     at android.hardware.Camera.autoFocus(Camera.java:1454)
10-09 12:01:28.014 3911-3911/com.mindpin.art_demo.samples W/System.err:     at com.mindpin.art_demo.samples.views.TakePhotoActivity.focus(TakePhotoActivity.java:117)
10-09 12:01:28.014 3911-3911/com.mindpin.art_demo.samples W/System.err:     at com.mindpin.art_demo.samples.views.TakePhotoActivity.onResume(TakePhotoActivity.java:451)
10-09 12:01:28.015 3911-3911/com.mindpin.art_demo.samples W/System.err:     at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1197)
10-09 12:01:28.015 3911-3911/com.mindpin.art_demo.samples W/System.err:     at android.app.Activity.performResume(Activity.java:5358)
10-09 12:01:28.015 3911-3911/com.mindpin.art_demo.samples W/System.err:     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2971)
10-09 12:01:28.016 3911-3911/com.mindpin.art_demo.samples W/System.err:     ... 12 more
10-09 12:01:28.016 3911-3911/com.mindpin.art_demo.samples W/dalvikvm: threadid=1: calling UncaughtExceptionHandler
10-09 12:01:28.018 3911-3911/com.mindpin.art_demo.samples E/AndroidRuntime: FATAL EXCEPTION: main
10-09 12:01:28.018 3911-3911/com.mindpin.art_demo.samples E/AndroidRuntime: Process: com.mindpin.art_demo.samples, PID: 3911
10-09 12:01:28.018 3911-3911/com.mindpin.art_demo.samples E/AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {com.mindpin.art_demo.samples/com.mindpin.art_demo.samples.views.TakePhotoActivity}: java.lang.RuntimeException: autoFocus failed
10-09 12:01:28.018 3911-3911/com.mindpin.art_demo.samples E/AndroidRuntime:     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2985)
10-09 12:01:28.018 3911-3911/com.mindpin.art_demo.samples E/AndroidRuntime:     at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3014)
10-09 12:01:28.018 3911-3911/com.mindpin.art_demo.samples E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2403)
10-09 12:01:28.018 3911-3911/com.mindpin.art_demo.samples E/AndroidRuntime:     at android.app.ActivityThread.access$800(ActivityThread.java:159)
10-09 12:01:28.018 3911-3911/com.mindpin.art_demo.samples E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1329)
10-09 12:01:28.018 3911-3911/com.mindpin.art_demo.samples E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:110)
10-09 12:01:28.018 3911-3911/com.mindpin.art_demo.samples E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:193)
10-09 12:01:28.018 3911-3911/com.mindpin.art_demo.samples E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5367)
10-09 12:01:28.018 3911-3911/com.mindpin.art_demo.samples E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method)
10-09 12:01:28.018 3911-3911/com.mindpin.art_demo.samples E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:515)
10-09 12:01:28.018 3911-3911/com.mindpin.art_demo.samples E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:847)
10-09 12:01:28.018 3911-3911/com.mindpin.art_demo.samples E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:663)
10-09 12:01:28.018 3911-3911/com.mindpin.art_demo.samples E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method)
10-09 12:01:28.018 3911-3911/com.mindpin.art_demo.samples E/AndroidRuntime:  Caused by: java.lang.RuntimeException: autoFocus failed
10-09 12:01:28.018 3911-3911/com.mindpin.art_demo.samples E/AndroidRuntime:     at android.hardware.Camera.native_autoFocus(Native Method)
10-09 12:01:28.018 3911-3911/com.mindpin.art_demo.samples E/AndroidRuntime:     at android.hardware.Camera.autoFocus(Camera.java:1454)
10-09 12:01:28.018 3911-3911/com.mindpin.art_demo.samples E/AndroidRuntime:     at com.mindpin.art_demo.samples.views.TakePhotoActivity.focus(TakePhotoActivity.java:117)
10-09 12:01:28.018 3911-3911/com.mindpin.art_demo.samples E/AndroidRuntime:     at com.mindpin.art_demo.samples.views.TakePhotoActivity.onResume(TakePhotoActivity.java:451)
10-09 12:01:28.018 3911-3911/com.mindpin.art_demo.samples E/AndroidRuntime:     at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1197)
10-09 12:01:28.018 3911-3911/com.mindpin.art_demo.samples E/AndroidRuntime:     at android.app.Activity.performResume(Activity.java:5358)
10-09 12:01:28.018 3911-3911/com.mindpin.art_demo.samples E/AndroidRuntime:     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2971)
10-09 12:01:28.018 3911-3911/com.mindpin.art_demo.samples E/AndroidRuntime:     at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3014) 
10-09 12:01:28.018 3911-3911/com.mindpin.art_demo.samples E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2403) 
10-09 12:01:28.018 3911-3911/com.mindpin.art_demo.samples E/AndroidRuntime:     at android.app.ActivityThread.access$800(ActivityThread.java:159) 
10-09 12:01:28.018 3911-3911/com.mindpin.art_demo.samples E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1329) 
10-09 12:01:28.018 3911-3911/com.mindpin.art_demo.samples E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:110) 
10-09 12:01:28.018 3911-3911/com.mindpin.art_demo.samples E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:193) 
10-09 12:01:28.018 3911-3911/com.mindpin.art_demo.samples E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5367) 
10-09 12:01:28.018 3911-3911/com.mindpin.art_demo.samples E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method) 
10-09 12:01:28.018 3911-3911/com.mindpin.art_demo.samples E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:515) 
10-09 12:01:28.018 3911-3911/com.mindpin.art_demo.samples E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:847) 
10-09 12:01:28.018 3911-3911/com.mindpin.art_demo.samples E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:663) 
10-09 12:01:28.018 3911-3911/com.mindpin.art_demo.samples E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method) 
```

---

初步判断是自动对焦代码存在问题

**Comment by destinyd** [comment]
已取消自动对焦，最新版本，百度云地址：

http://pan.baidu.com/s/1bnluPUf
