### ISSUE TITLE
使用OpenCV进行矩形识别，以达到自动识别画纸并拍照的效果

### ISSUE THREAD

**Issue by destinyd** [mindpin/knowledge-camp-art#9]
最终成型效果，参考支付宝【添加新卡】【拍照添加】

就网络资料来看，识别基本都是通过opencv来实现，所以现在也朝这个方面努力

**Comment by destinyd** [comment]
Android opencv 安装与环境搭建

官方文档

中文参考

以上均为使用 Eclipse 开发，并没有 maven 相关信息。照原开发形式，还得再研究怎么在项目里引入 OpenCV

注意事项:

要在Android机上能正常使用OpenCV，以下两者取其一：
1. 安装OpenCV ManagerAPK
2. 通过JNI编译，不再动态引用，而是引用静态链接库。参考文献

**Comment by destinyd** [comment]
### Intellij Idea 引入 OpenCV Android (Mac Book Pro, OS X 10.11)

系统 homebrew 安装

``` shell
brew install homebrew/science/opencv
brew info opencv
```

返回

```
homebrew/science/opencv: stable 2.4.12, HEAD
Open source computer vision library
http://opencv.org/
/usr/local/Cellar/opencv/2.4.12 (225 files, 36M) *
  Built from source
From: https://github.com/Homebrew/homebrew-science/blob/master/opencv.rb
```

**./art-demo-samples/pom.xml**
加入

``` xml
        <dependency>
            <groupId>nu.pattern</groupId>
            <artifactId>opencv</artifactId>
            <version>2.4.9-7</version>
            <exclusions>
                <exclusion>
                    <groupId>com.google.android</groupId>
                    <artifactId>support-v4</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

这里版本最高却又只有 **2.4.9-7**，引入之后可以看到 Java 对于 OpenCV 最基本的引用了(org.opencv.utils)

暂且不理会版本可能会出现的问题

下载了 **2.4.11** 的 OpenCV for android，解压缩，将其解压包的 **./sdk/java/** 目录引入项目，并在 samples 里添加对其的依赖，及可看到了 **org.opencv.android** 等 OpenCV for Android 的包了。  

但是编译之后报错，先是缺少 Android 依赖，添加上去之后，又报了其他错误：

```
Information:15/10/19 上午1:06 - Compilation completed with 17 errors and 0 warnings in 8s 492ms
Error:Android Dex: [art-demo-samples] Unable to execute DX
Error:Android Dex: [art-demo-samples] com.android.dex.DexException: Multiple dex files define Lorg/opencv/calib3d/Calib3d;
Error:Android Dex: [art-demo-samples] at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:594)
Error:Android Dex: [art-demo-samples] at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:552)
Error:Android Dex: [art-demo-samples] at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:533)
Error:Android Dex: [art-demo-samples] at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:170)
Error:Android Dex: [art-demo-samples] at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
Error:Android Dex: [art-demo-samples] at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:439)
Error:Android Dex: [art-demo-samples] at com.android.dx.command.dexer.Main.runMonoDex(Main.java:287)
Error:Android Dex: [art-demo-samples] at com.android.dx.command.dexer.Main.run(Main.java:230)
Error:Android Dex: [art-demo-samples] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Error:Android Dex: [art-demo-samples] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Error:Android Dex: [art-demo-samples] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Error:Android Dex: [art-demo-samples] at java.lang.reflect.Method.invoke(Method.java:483)
Error:Android Dex: [art-demo-samples] at org.jetbrains.android.compiler.tools.AndroidDxRunner.runDex(AndroidDxRunner.java:161)
Error:Android Dex: [art-demo-samples] at org.jetbrains.android.compiler.tools.AndroidDxRunner.main(AndroidDxRunner.java:294)
Error:Android Dex: [art-demo-samples] at com.intellij.rt.execution.CommandLineWrapper.main(CommandLineWrapper.java:130)
```

初步估计是缺少某些依赖，或者动态链接库什么的，找了很久找不到答案。  
两天找到了怎么引入，但是在解决这个错误上，没有什么太大进展

**Comment by destinyd** [comment]
改用OpenCV 3.0.0

**Homebrew** 删除 OpenCV 后，安装 OpenCV3

``` shell
brew uninstall homebrew/science/opencv
brew install homebrew/science/opencv3
```

**./art-demo-samples/pom.xml**
改为

``` xml
        <dependency>
            <groupId>org.bytedeco.javacpp-presets</groupId>
            <artifactId>opencv</artifactId>
            <version>3.0.0-1.0</version>
            <exclusions>
                <exclusion>
                    <groupId>com.google.android</groupId>
                    <artifactId>support-v4</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

代码加上

``` java

    BaseLoaderCallback callback = new BaseLoaderCallback(this) {
        @Override
        public void onManagerConnected(int status) {
            switch ( status ) {

                case LoaderCallbackInterface.SUCCESS: {
                    Log.i("Yay", "OpenCV loaded successfully");
                    break;
                }
                default: {
                    super.onManagerConnected(status);
                }
            }
        }
    };


    @Override
    protected void onResume() {
        super.onResume();
        OpenCVLoader.initAsync(OpenCVLoader.OPENCV_VERSION_3_0_0, this, callback);
    }
```

先安装 OpenCV for Android 3.0.0/apk/OpenCV_3.0.0_Manager_3.00_armeabi-v7a.apk （for MiPad）

然后编译运行代码，Log里成功显示 **OpenCV loaded successfully** 即加载成功。

**Comment by destinyd** [comment]
### 编写JNI以及C相关代码

参考文章： http://blog.csdn.net/pwh0996/article/details/8957764

**jni/Android.mk**

```
LOCAL_PATH := $(call my-dir)  
include $(CLEAR_VARS)  
include ../OpenCV-SDK/native/jni/OpenCV.mk  
LOCAL_SRC_FILES  := ImageProc.cpp  
LOCAL_MODULE     := image_proc  
include $(BUILD_SHARED_LIBRARY)  
···

**jni/Application.mk**
```

APP_STL := gnustl_static  
APP_CPPFLAGS := -frtti -fexceptions
APP_ABI := armeabi-v7a
APP_PLATFORM := android-8 

``````

**jni/ImageProc.cpp**
```cpp
#include <ImageProc.h>
#include <opencv2/core/core.hpp>
#include <string>
#include <vector>

using namespace cv;
using namespace std;

JNIEXPORT jintArray JNICALL Java_com_iron_grayprocess2_ImageProc_grayProc(JNIEnv* env, jclass obj, jintArray buf, jint w, jint h){
    jint *cbuf;
    cbuf = env->GetIntArrayElements(buf, false);
    if(cbuf == NULL){
        return 0;
    }

    Mat imgData(h, w, CV_8UC4, (unsigned char*)cbuf);

    uchar* ptr = imgData.ptr(0);
    for(int i = 0; i < w*h; i ++){
        //计算公式：Y(亮度) = 0.299*R + 0.587*G + 0.114*B
        //对于一个int四字节，其彩色值存储方式为：BGRA
        int grayScale = (int)(ptr[4*i+2]*0.299 + ptr[4*i+1]*0.587 + ptr[4*i+0]*0.114);
        ptr[4*i+1] = grayScale;
        ptr[4*i+2] = grayScale;
        ptr[4*i+0] = grayScale;
    }

    int size=w * h;
    jintArray result = env->NewIntArray(size);
    env->SetIntArrayRegion(result, 0, size, cbuf);
    env->ReleaseIntArrayElements(buf, cbuf, 0);
    return result;
}
``````

**jni/ImageProc.h**

``` cpp
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mindpin_art_demo_samples_ImageProc */

#ifndef _Included_com_mindpin_art_demo_samples_ImageProc
#define _Included_com_mindpin_art_demo_samples_ImageProc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mindpin_art_demo_samples_ImageProc
 * Method:    grayProc
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_mindpin_art_1demo_samples_ImageProc_grayProc
  (JNIEnv *, jclass, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
```

**注意：jni/Application.mk 里， OpenCV ANDROID SDK路径需要设置好**

然后在项目里运行 **$NDKROOT/ndk-build**

在需要读取的Activity里面

``` java

    BaseLoaderCallback callback = new BaseLoaderCallback(this) {
        @Override
        public void onManagerConnected(int status) {
            switch ( status ) {

                case LoaderCallbackInterface.SUCCESS: {
                    System.loadLibrary("image_proc");
                    break;
                }
                default: {
                    super.onManagerConnected(status);
                }
            }
        }
    };


    @Override
    protected void onResume() {
        super.onResume();
        OpenCVLoader.initAsync(OpenCVLoader.OPENCV_VERSION_3_0_0, this, callback);
    }


    @Override  
    public void onClick(View v) {  
        int w = bmp.getWidth();  
        int h = bmp.getHeight();  
        int[] pixels = new int[w*h];       
        bmp.getPixels(pixels, 0, w, 0, 0, w, h);  
        int[] resultInt = ImageProc.grayProc(pixels, w, h);  
        Bitmap resultImg = Bitmap.createBitmap(w, h, Config.ARGB_8888);  
        resultImg.setPixels(resultInt, 0, w, 0, 0, w, h);  
        imageView.setImageBitmap(resultImg);      
    }  
```

编译APK，运行成功

**Comment by destinyd** [comment]
识别矩形参考文章：

[识别与跟踪图片-版本2.4.4-纯Android](http://blog.csdn.net/ggtaas/article/details/38355665)

[opencv 检测直线、圆、矩形-版本未知-纯C++](http://blog.csdn.net/byxdaz/article/details/4912136)  
[opencv识别正方形（矩形）代码-版本未知-纯C++](http://blog.csdn.net/byxdaz/article/details/4912136)

**Comment by destinyd** [comment]
原计划通过OpenCV识别一定斜角角度内的矩形，捕捉到后，自动拍照、截取范围内图片。

但是暂时能找到的资料均为2.x.x版本的。

如果要学习3.0.0，又需要较多的时间成本，打算暂时先搁置

**Comment by destinyd** [comment]
### OpenCV 3.0.0,直接操作Preview

此示例主要为教如何处理JNI与Activity函数结合，并操作Preview界面
用意：**构建仿支付宝扫描银行卡方框**

**src/com/mindpin/art_demo/samples/views/TakePhotoActivity.java**

``` java
package com.mindpin.art_demo.samples.views;

import android.app.Activity;
import android.os.Bundle;
import android.util.Log;
import android.view.WindowManager;
import org.opencv.android.*;
import org.opencv.core.Mat;

@SuppressWarnings("deprecation")
public class TakePhotoActivity extends Activity  implements CameraBridgeViewBase.CvCameraViewListener {
    //定义log标签
    private static String TAG = "doudou";
    //摄像头对象
    private CameraBridgeViewBase mOpenCvCameraView;
    //native 方法
    public static native void drawRect(long bitmap);

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        //屏幕常亮
        getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);
        mOpenCvCameraView = (CameraBridgeViewBase) new JavaCameraView(this, -1);
        //设置摄像头为布局样式
        setContentView(mOpenCvCameraView);
        //摄像头监听事件，利用这个监听事件调用我们的native方法，从而对每一帧在native层进行处理
        mOpenCvCameraView.setCvCameraViewListener(this);
    }

    @Override
    public void onResume()
    {
        super.onResume();
        if (!OpenCVLoader.initDebug()) {
            Log.d(TAG, "Internal OpenCV library not found. Using OpenCV Manager for initialization");
            OpenCVLoader.initAsync(OpenCVLoader.OPENCV_VERSION_3_0_0, this, mLoaderCallback);
        } else {
            Log.d(TAG, "OpenCV library found inside package. Using it!");
            mLoaderCallback.onManagerConnected(LoaderCallbackInterface.SUCCESS);
        }
    }

    private BaseLoaderCallback mLoaderCallback = new BaseLoaderCallback(this) {

        @Override
        public void onManagerConnected(int status) {
            switch (status) {
                case LoaderCallbackInterface.SUCCESS:
                {
                    Log.i("doudou", "OpenCV loaded successfully");
                    System.loadLibrary("firstopencv");
                    Log.i("doudou", "libfirstopencv.so loaded successfully");
                    mOpenCvCameraView.enableView();
                } break;
                default:
                {
                    super.onManagerConnected(status);
                } break;
            }
        }
    };

    public void onCameraViewStarted(int width, int height) {
    }
    public void onCameraViewStopped() {
    }


    public Mat onCameraFrame(Mat inputFrame) {
        //获取mat地址
        long address = inputFrame.getNativeObjAddr();
        //使用native方法对地址指向的mat矩阵进行绘制操作
        drawRect(address);
        //根据该地址生成mat
        Mat histogram = new Mat(address);
        //返回给屏幕
        return histogram;
    }
}
```

**jni/firstopencv.cpp**

``` cpp
#include "com_mindpin_art_demo_samples_views_TakePhotoActivity.h"
#include "opencv2/opencv.hpp"
using namespace cv;
JNIEXPORT void JNICALL Java_com_mindpin_art_1demo_samples_views_TakePhotoActivity_drawRect
  (JNIEnv *env, jclass jclas, jlong jlon){
    Mat *bitmpaMat = (Mat*) jlon;
    rectangle(*bitmpaMat,Point(300,300),Point(600,600),Scalar(222,222,222),4);
}
```

**jni/Android.mk**

```
LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)
include ../OpenCV-android-sdk-3.0.0/sdk/native/jni/OpenCV.mk
LOCAL_SRC_FILES  := firstopencv.cpp
LOCAL_MODULE     := firstopencv
include $(BUILD_SHARED_LIBRARY)
```

在项目运行,生成 **.h**头，用于编译

``` shell
javah -classpath ./src -d jni -jni com.mindpin.art_demo.samples.views.TakePhotoActivity
```

编译

``` shell
ndk-build
```

会看到生成 **libs/armeabi-v7a/libfirstopencv.so** 文件

然后重新编译APK，即可看到加了方框的Preview

![opencv](http://i.teamkn.com/i/b2T8D3N2.jpg)
